#!/usr/bin/env bash
# This script uses unit loop to displays "Best School" 10 time
count=1
until [ $count -gt 10 ]
do
  : $count   # dummy use to satisfy ShellCheck
  echo "Best School"
  count=$((count + 1))
done

