#!/usr/bin/env bash
# This script displays "Best School" 10 times, but shows "Best school" and "Hi" on the 9th iteration
count=1
while [ $count -le 10 ]
do
  : $count   # dummy use to satisfy ShellCheck
  if [ $count -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done
